// models/Captain.js
const mongoose = require('mongoose');

const CaptainSchema = new mongoose.Schema({
    captainId: { type: String, required: true, unique: true }, // auto-generated by admin
    studentId: { type: mongoose.Schema.Types.ObjectId, ref: 'Student', required: true }, // link to student
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    phone: { type: String },
    
    sport: { type: String, required: true }, // e.g., Football, Basketball
    teamName: { type: String, required: true },
    academicYear: { type: Number, required: true }, // session-wise
    semester: { type: Number, required: true },
    
    players: [
        {
            studentId: { type: mongoose.Schema.Types.ObjectId, ref: 'Student', required: true },
            name: String,
            position: String, // e.g., Goalkeeper, Forward
            year: Number,
            department: String
        }
    ],

    tournaments: [
        {
            tournamentId: { type: mongoose.Schema.Types.ObjectId, ref: 'Tournament' },
            name: String,
            year: Number,
            status: { type: String, enum: ['upcoming', 'completed'], default: 'upcoming' }
        }
    ],

    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'Admin', required: true }, // admin who created captain
    createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Captain', CaptainSchema);
