// models/Captain.js
const mongoose = require('mongoose');

const CaptainSchema = new mongoose.Schema({
    captainId: { type: String, required: true, unique: true }, // auto-generated by backend
    name: { type: String, required: true }, // assigned by admin
    branch: { type: String, required: true }, // assigned by admin
    urn: { type: String, required: true, unique: true }, // assigned by admin
    year: { type: Number, required: true }, // assigned by admin
    sport: { type: String, required: true }, // assigned by admin
    teamMemberCount: { type: Number, required: true }, // assigned by admin

    // Filled by captain on first login
    email: { type: String },
    phone: { type: String },

    // After first form submission → team member info
    teamMembers: [
        {
            name: { type: String, required: true },
            branch: { type: String, required: true },
            urn: { type: String, required: true },
            year: { type: Number, required: true },
            email: { type: String, required: true },
            phone: { type: String, required: true }
        }
    ],

    session: { type: mongoose.Schema.Types.ObjectId, ref: 'Session', required: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'Admin', required: true },
    createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Captain', CaptainSchema);
