const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
  name: String,
  email: { type: String, unique: true },
  password: String,
  role: { 
    type: String, 
    enum: ['admin', 'teacher', 'student', 'captain'], 
    required: true 
  },
  studentProfile: { type: mongoose.Schema.Types.ObjectId, ref: 'StudentProfile' },

  // Captain-specific
  captainId: { type: String, unique: true, sparse: true }, // auto-generated by admin
  captainProfile: { type: mongoose.Schema.Types.ObjectId, ref: 'CaptainProfile' } // filled later by captain
}, 
{ timestamps: true });

module.exports = mongoose.model('User', UserSchema);
